version: '3'

services:
  # Define a collectd service
  collectd:
    image: onesourceintegrations/collectd
    privileged: yes
    volumes:
      - ./etc/collectd.conf:/etc/collectd.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"

  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.3.5
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  # Define a grafana service
  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"
    links:
      - influxdb
